version: '2'
services:
    hipsample-app:
        image: hipsample
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://hipsample-mysql:3306/hipsample?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=hipsample-elasticsearch:9300
        ports:
            - 8080:8080
    hipsample-mysql:
        extends:
            file: mysql.yml
            service: hipsample-mysql
    hipsample-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: hipsample-elasticsearch
